/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_jni_androidstudio_jni_MainActivity */

#ifndef _Included_com_android_jni_androidstudio_jni_MainActivity
#define _Included_com_android_jni_androidstudio_jni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_jni_androidstudio_jni_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_jni_androidstudio_1jni_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
